// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZxnDR77kIrrqeBkX1hJI0l8DN5TmoAM',
    appId: '1:985416533716:web:c09b3f7051dd97d8255d41',
    messagingSenderId: '985416533716',
    projectId: 'myfamily-d1388',
    authDomain: 'myfamily-d1388.firebaseapp.com',
    storageBucket: 'myfamily-d1388.firebasestorage.app',
    measurementId: 'G-VHN8B7S66E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACO267gaBdgFAcXAXCaHN_MHSNSxkktjU',
    appId: '1:985416533716:android:4cf45b78dd473275255d41',
    messagingSenderId: '985416533716',
    projectId: 'myfamily-d1388',
    storageBucket: 'myfamily-d1388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhk0ZL-oZDvqOsLjTqNR2mpNiPEP5J1s',
    appId: '1:985416533716:ios:2164d5a7d5ee1287255d41',
    messagingSenderId: '985416533716',
    projectId: 'myfamily-d1388',
    storageBucket: 'myfamily-d1388.firebasestorage.app',
    androidClientId: '985416533716-aovmnhh45glq9oos67c5nlgql6lmllf7.apps.googleusercontent.com',
    iosClientId: '985416533716-n3cn247pk6ftagt9c7kdq3h4k3fqj0nu.apps.googleusercontent.com',
    iosBundleId: 'com.familyapp.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhk0ZL-oZDvqOsLjTqNR2mpNiPEP5J1s',
    appId: '1:985416533716:ios:fe78af926619bf12255d41',
    messagingSenderId: '985416533716',
    projectId: 'myfamily-d1388',
    storageBucket: 'myfamily-d1388.firebasestorage.app',
    androidClientId: '985416533716-aovmnhh45glq9oos67c5nlgql6lmllf7.apps.googleusercontent.com',
    iosClientId: '985416533716-lqpp06d2auhmd4cvl7ap4qrbbob2cle5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZxnDR77kIrrqeBkX1hJI0l8DN5TmoAM',
    appId: '1:985416533716:web:dcde4c0695971d75255d41',
    messagingSenderId: '985416533716',
    projectId: 'myfamily-d1388',
    authDomain: 'myfamily-d1388.firebaseapp.com',
    storageBucket: 'myfamily-d1388.firebasestorage.app',
    measurementId: 'G-JNHZT0FWVE',
  );
}
