import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/services/role_permission_service.dart';
import '../models/recipe_model.dart';
import 'family_repository.dart';

class RecipeRepository {
  final SupabaseClient _supabase = Supabase.instance.client;
  final RolePermissionService _roleService = RolePermissionService();
  final FamilyRepository _familyRepository = FamilyRepository();

  /// Create a new recipe
  Future<RecipeModel> createRecipe({
    required String familyId,
    required String title,
    String? description,
    int? prepTimeMinutes,
    int? cookTimeMinutes,
    int servings = 4,
    List<Map<String, dynamic>>? ingredients,
    List<String>? instructions,
    List<String>? tags,
    String? imageUrl,
    String? sourceUrl,
  }) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId == null) throw Exception('User not logged in');

    // Any family member can create a recipe (assumption: open contribution)
    // We could restrict to parents if needed, but recipes usually shared.

    final recipe = RecipeModel(
      id: '', // Generated by DB
      familyId: familyId,
      title: title,
      description: description,
      prepTimeMinutes: prepTimeMinutes,
      cookTimeMinutes: cookTimeMinutes,
      servings: servings,
      ingredients: ingredients,
      instructions: instructions,
      tags: tags,
      imageUrl: imageUrl,
      sourceUrl: sourceUrl,
      createdBy: userId,
    );

    final response = await _supabase
        .from('recipes')
        .insert(RecipeModelHelpers.toSupabase(recipe))
        .select()
        .single();

    return RecipeModelHelpers.fromSupabase(response);
  }

  /// Update an existing recipe
  Future<RecipeModel> updateRecipe(RecipeModel recipe) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId == null) throw Exception('User not logged in');

    // Check if user is creator or parent/admin? For now, allow any family member.
    // In strict mode, we'd check permissions.

    final response = await _supabase
        .from('recipes')
        .update(RecipeModelHelpers.toSupabase(recipe))
        .eq('id', recipe.id)
        .select()
        .single();

    return RecipeModelHelpers.fromSupabase(response);
  }

  /// Delete a recipe
  Future<void> deleteRecipe(String recipeId) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId == null) throw Exception('User not logged in');

    await _supabase.from('recipes').delete().eq('id', recipeId);
  }

  /// Stream recipes for a family
  Stream<List<RecipeModel>> streamRecipes(String familyId) {
    return _supabase
        .from('recipes')
        .stream(primaryKey: ['id'])
        .eq('family_id', familyId)
        .order('created_at', ascending: false)
        .map(
          (data) => data
              .map((json) => RecipeModelHelpers.fromSupabase(json))
              .toList(),
        );
  }

  /// Get a single recipe by ID
  Future<RecipeModel?> getRecipe(String recipeId) async {
    try {
      final response = await _supabase
          .from('recipes')
          .select()
          .eq('id', recipeId)
          .single();
      return RecipeModelHelpers.fromSupabase(response);
    } catch (e) {
      return null;
    }
  }
}
